[package]
name = "matrix_script"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { version = "0.5.0", features = ["llvm17-0-prefer-dynamic"] }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
logos = "0.14"
thiserror = "1.0"
